---
# Ansible Playbook to upgrade Cisco IOS
- name: Upgrade CISCO IOS
  connection: local
  hosts: device

  vars:
    upgrade_ios_version: 15.0(2a)EX5

  tasks:
    - name: CHECK CURRENT Version
      ios_facts:
    
    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is 15.2.7E3 (MD)"

    - debug:
        msg:
        - "Image is not compliant and will be upgraded"
      
      when: ansible_net_version != upgrade_ios_version

## Create backup folder for today

- hosts: device
  connection: local

  tasks:
  - name: Get ansible date/time facts
    shell: "date +%Y-%m-%d%H-%M-%S"
    register: tstamp
      
  - name: Store DTG as fact
    set_fact:
      DTG: "{{ tstamp.stdout[0:10] }}"

  - name: 
    debug:
      msg: "Current date : {{DTG }}"

# - name: Create Directory {{DTG}}
#  file:
#    path: ~/home/engineer1/ios-upgrade/backups/{{DTG}}
#    state: directory
# run_once: true

## Backup the Running Config and enable scp server on switch.

- hosts: device
  connection: local

  tasks:
    - name: Backup Running Config
      ios_command:
        commands: show run
        
      register: config
    - name: Save output to ./backups/
      copy:
        content: "{{config.stdout[0]}}"
        dest: "./backups/{{ inventory_hostname }}-{{DTG}}-config.txt"

## Save the Running Config

    - name: Save the running config
      ios_config:
        save_when: always

## Enable the scp server to transfer the file to the switch
- hosts: device
  connection: local

  tasks:
    - name: Backup Running Config
      cisco.ios.ios_command:
        commands:
        - config t
        - ip scp server enable

## Copy software to target device 
 
    - name: Copy Image // This could take up to 4 minutes
      net_put:
        src: "~/home/engineer1/ios-upgrade/images/c2960x-universalk9-tar.152-7.E3.tar"
        dest: "flash:/c2960x-universalk9-tar.152-7.E3.tar"
      vars:
        ansible_command_timeout: 600